language: php
php:
- '5.5'
- '5.4'
before_install:
- openssl aes-256-cbc -K $encrypted_fee1ab4be628_key -iv $encrypted_fee1ab4be628_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- composer install

after_success:
- ssh ubuntu@119.29.240.215 'cd /mnt/www && git clone git@github.com:TIGERB/travis-test.git'
